# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-json
      - id: pretty-format-json
        args: [--autofix, --indent, "2", --no-ensure-ascii, --no-sort-keys]
        exclude: |
          (?x)(
            .jshintrc$|
          )
      - id: check-vcs-permalinks
      - id: debug-statements
      - id: detect-private-key
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending  # force UNIX file endings for consistency
        args: [--fix=lf]
      - id: check-executables-have-shebangs
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.29.0
    hooks:
      - id: yamllint
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.33.0
    hooks:
      - id: markdownlint-fix
  - repo: https://github.com/martyzz1/pre-commit-hooks
    rev: v1.8
    hooks:
      - id: prepend-branch-name
      - id: circleci-config-validate
        # args: ["--org-slug", "github/harper-concierge"]
      - id: circleci-orb-pack-validation
  - repo: https://github.com/Lucas-C/pre-commit-hooks-markup
    rev: v1.0.1
    hooks:
      - id: rst-linter
        args: [--allow-raw]
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: shellcheck
